name: Tests

on: [push, pull_request]

jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            rev: nightly/nvim-linux64.tar.gz
          - os: ubuntu-22.04
            rev: v0.9.0/nvim-linux64.tar.gz
          - os: macos-12
            rev: nightly/nvim-macos.tar.gz
          - os: macos-12
            rev: v0.9.0/nvim-macos.tar.gz
    steps:
      - uses: actions/checkout@v3
      - run: date +%F > todays-date
      - name: Restore from todays cache
        uses: actions/cache@v3
        with:
          path: _neovim
          key: ${{ runner.os }}-${{ matrix.rev }}-${{ hashFiles('todays-date') }}

      - name: Prepare
        run: |
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL "https://github.com/neovim/neovim/releases/download/${{ matrix.rev }}" | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }
          test -d _plenary || {
            mkdir -p _neovim/share/nvim/site/pack/packages/start
            git clone https://github.com/nvim-lua/plenary.nvim _neovim/share/nvim/site/pack/packages/start/plenary.nvim
          }
      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          make test
